package model.s02;

import jakarta.persistence.Enumerated;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import model.constant.MembershipLevel;

@Entity
public class GymMembership {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@Enumerated(EnumType.STRING) // EnumType : Enum을 DB에 반영하기 위한 전략
	// ORDINAL : ENUM의 이름이 아닌 순서인덱스로 반영하게 됨
	//  -> String 사용

	// STRING :  ENUM의 이름으로 반영 -> 주로 사용
	private MembershipLevel membershipLevel;
	//
	// [Hibernate]
	// create table GymMembership (
	// 	id bigint generated by default as identity,
	// 	membershipLevel enum ('BRONZE','GOLD','SILVER'),
	// primary key (id)
  //   )

}
